services:
  clash-server:
    image: mangydog/clash
    container_name: clash-server
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    ports:
      - "7890:7890"
      - "9090:9090" # external controller (Restful API)
    restart: unless-stopped

  clash-web:
    image: mangydog/yacd
    container_name: clash-web
    ports:
      - "8090:80"
    restart: unless-stopped
    depends_on:
      - clash-server
